name: Testes
run-name: ${{github.actor}} fez commit no projeto
on: [push]
jobs:
build:
runs-on: ubuntu-latest
steps:
#versão do GitHub actions
- uses: actions/checkout@v4
- name: Configurando o Python
# versão do actions para o python
uses: actions/setup-python@v5
with:
python-version: '3.10'
architecture: 'x64'
- name: Instalando a coverage
run: python -m unittest discover