name: Testes
run-name: ${{github.actor}} fez commit no projeto
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # versão do GitHub actions
      - uses: actions/checkout@v4
      - name: Configurando o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      
      # Instalando a coverage
      - name: Instalando a coverage
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      # Rodando os testes
      - name: Rodando os testes com unittest
        run: python -m unittest discover
